site_name: Chainmock docs
site_description: chainmock - Mocking library for Python and Pytest
site_url: https://chainmock.readthedocs.io/en/latest/
theme:
  name: material
  logo: assets/icon_white.png
  favicon: assets/icon_black.png
  features:
    - content.code.annotate
    - navigation.expand
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
extra_css:
  - assets/extra.css
repo_name: chainmock
repo_url: https://github.com/ollipa/chainmock
edit_uri: ""
watch:
  - README.md
  - CONTRIBUTING.md
  - CHANGELOG.md
hooks:
  - docs/hooks/hide_lines.py

nav:
  - Overview: index.md
  - User Guide:
      - Getting started: user_guide/getting_started.md
      - Argument matching: user_guide/argument_matching.md
      - Async mocking: user_guide/async_mocking.md
      - Mocking properties: user_guide/mocking_properties.md
      - Mocking modules: user_guide/mocking_modules.md
      - Advanced usage: user_guide/advanced_usage.md
  - Contributing: contributing.md
  - Changelog: changelog.md
  - API reference: api_reference.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            filters:
              - "!^_" # exlude all members starting with _
            show_source: false
            show_root_heading: true
            show_root_full_path: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - markdown_include.include:
      base_path: docs
